apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-frontend
  template:
    metadata:
      labels:
        app: sa-frontend
    spec:
      containers:
      - image: petrolnt/sentiment-analysis-frontend
        imagePullPolicy: Always
        name: sa-frontend
        ports:
          - containerPort: 80

  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  

